name: lint

on:
  - push
  - pull_request

jobs:
  cpp-lint:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - uses: actions/checkout@v4
      - name: Install stuff
        run: |
          apk add --no-cache clang-extra-tools linux-headers make openjdk11-jdk python3 bash
      - name: Run clang-tidy
        run: |
          make cpp-lint LINT_DIFF_ONLY=false CLANG_TIDY_FLAGS="--export-fixes=clang_tidy_out.yaml"
          cat clang_tidy_out.yaml
      - name: PR comments
        uses: fandreuz/clang-tidy-pr-comments@link
        with:
          # The GitHub token (or a personal access token)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The path to the clang-tidy fixes generated previously
          clang_tidy_fixes: clang_tidy_out.yaml
