name: CI

on:  # We are very liberal in terms of triggering builds. This should be revisited if we start seeing a lot of queueing
  - push
  - pull_request

env:
  java_default_distribution: corretto
  java_default_version: 11

jobs:
  build-jars:
    runs-on: ubuntu-latest
    name: Build JARs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build JARs
        run: make jar
      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: async-profiler-jars
          path: build/jar/*
          if-no-files-found: error
  build-and-upload-binaries:
    strategy:
      matrix:
        include:
          - runson:
              display: amazonlinux2
              name: ubuntu-latest
            image: public.ecr.aws/async-profiler/asprof-builder-amazonlinux:2
    runs-on: ${{ matrix.runson.name }}
    container:
      image: ${{ matrix.image }}
    name: "Build and unit test (${{ matrix.runson.display }})"
    steps:
      - name: Run container setup
        run: echo "/usr/local/bin:$GITHUB_PATH" >> $GITHUB_PATH
      - name: Echo path
        run: |
          echo $PATH
          which node
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution || env.java_default_distribution }}
          java-version: ${{ matrix.java-version || env.java_default_version }}
      - name: Checkout sources
        uses: actions/checkout@v4
