name: CI

on:  # We are very liberal in terms of triggering builds. This should be revisited if we start seeing a lot of queueing
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  java_default_distribution: corretto
  java_default_version: 11

jobs:
  build-jars:
    runs-on: ubuntu-latest
    name: Build JARs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build JARs
        run: make jar
      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: async-profiler-jars
          path: build/jar/*
          if-no-files-found: error
  build-and-upload-binaries:
    strategy:
      matrix:
        include:
          - runson:
              display: linux-arm64
              name: ubuntu-24.04-arm
            image: "public.ecr.aws/async-profiler/asprof-builder-arm:latest"
          - runson:
              display: linux-x64
              name: ubuntu-latest
            image: public.ecr.aws/async-profiler/asprof-builder-x86:latest
          - runson:
              display: macos
              name: macos-15
    runs-on: ${{ matrix.runson.name }}
    container:
      image: ${{ matrix.image }}
      volumes: ${{ fromJSON(matrix.volumes || '[]') }}
    name: "Build and unit test (${{ matrix.runson.display }})"
    steps:
      - name: Run container setup
        run: "[ ! -f /root/setup.sh ] || /root/setup.sh"
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution || env.java_default_distribution }}
          java-version: ${{ matrix.java-version || env.java_default_version }}
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build and unit test
        id: build
        run: |
          set -x
          HASH=${GITHUB_SHA:0:7}
          case "${{ matrix.runson.display }}" in
            macos*)
              brew install gcovr
              make COMMIT_TAG=$HASH FAT_BINARY=true release coverage -j
            ;;
            *)
              make COMMIT_TAG=$HASH CC=/usr/local/musl/bin/musl-gcc release coverage -j
              echo "debug_archive=$(find . -type f -name "async-profiler-*-debug*" -exec basename {} \;)" >> $GITHUB_OUTPUT
            ;;
          esac
          echo "archive=$(find . -type f -name "async-profiler-*" -not -name "*-debug*" -exec basename {} \;)" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_SHA: ${{ github.sha }}
      - name: Set artifact name
        id: set_artifact_name
        run: echo "artifact_name=async-profiler-${{ matrix.runson.display }}-${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_SHA: ${{ github.sha }}
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact_name.outputs.artifact_name }}
          path: ${{ steps.build.outputs.archive }}
          if-no-files-found: error
      - name: Upload debug info
        uses: actions/upload-artifact@v4
        if: matrix.runson.display != 'macos'
        with:
          name: ${{ steps.set_artifact_name.outputs.artifact_name }}-debug
          path: ${{ steps.build.outputs.debug_archive }}
          if-no-files-found: error
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-${{ matrix.runson.display }}
          path: build/test/coverage/
          if-no-files-found: error
  publish-nightly-github-release:
    name: publish (nightly)
    runs-on: ubuntu-latest
    needs: [build-jars, build-and-upload-binaries]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download async-profiler binaries and jars
        uses: actions/download-artifact@v4
        with:
          pattern: 'async-profiler-*'
          merge-multiple: 'true'
      - name: Create directory structure for Maven release
        run: |
          find . -type f -name "async-profiler-*.tar.gz" -not -name "*debug*" -exec tar -xf {} \;
          find . -type f -name "async-profiler-*.zip" -not -name "*debug*" -exec unzip {} \;
          for file in async-profiler-*/lib/*.{so,dylib};
            arch=$(python3 -c 'import sys; print("-".join(sys.argv[1].split("/")[0].split("-")[4:]))' "$file")
            ln -s $arch "$file/.."
          done
          ls
          ls linux-x64
        shell: bash
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Maven MacOS release
        run: |
          mvn versions:set -DnewVersion=${GITHUB_REF_NAME#v} -Dnative.platform=macos
          mvn deploy
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven linux-x64 release
        run: |
          mvn versions:set -DnewVersion=${GITHUB_REF_NAME#v} -Dnative.platform=linux-x64
          mvn deploy
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven linux-arm64 release
        run: |
          mvn versions:set -DnewVersion=${GITHUB_REF_NAME#v} -Dnative.platform=linux-arm64
          mvn deploy
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven jfr-converter release
        run: |
          mvn -f pom-converter.xml clean
          mvn -f pom-converter.xml versions:set -DnewVersion=${GITHUB_REF_NAME#v}
          mvn -f pom-converter.xml deploy
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
